apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-depl
  namespace: hackmd-dump
  labels:
    app: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - name: chrome
        image: alpeware/chrome-headless-trunk:rev-851733
        ports:
        - containerPort: 9222
---
apiVersion: v1
kind: Service
metadata:
  name: chrome-svc
  namespace: hackmd-dump
spec:
  selector:
    app: chrome
  ports:
  - protocol: TCP
    port: 9222
    targetPort: 9222
